version: '3.2'

services:
  api:
    container_name: controle-financeiro-api
    build: .
    command: sh -c "yarn && yarn start:dev"
    environment:
      #APP
      NODE_ENV: development
    depends_on:
      - mongo
    volumes:
      - .:/app
      - ~/.config:/root/.config
      - /node_modules
    ports:
      - '3000:3000'
  mongo:
    container_name: finance_api
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo